/// <summary>
/// A Simple Hello World Asset that is tied to Cocos2D
/// 
/// Based on a pattern in http://addyosmani.com/resources/essentialjsdesignpatterns/book/.
/// </summary>
///
/// <returns>
/// An instance of this Asset class.
/// </returns>
function Asset() {

    /// <summary>
    /// Manager for asset.
    /// </summary>
    var assetManager = AssetManager.getInstance();

    /// <summary>
    /// Backing field for the unique identifier.
    /// </summary>
    var _sId = "";

    /// <summary>
    /// Read-only property, returns name of this class.
    /// 
    /// See http://blog.magnetiq.com/post/514962277/finding-out-class-names-of-javascript-objects.
    /// </summary>
    ///
    /// <param name="this">    this. </param>
    /// <param name=""class""> The "class". </param>
    Object.defineProperty(this, "class", {
        enumerable: true,
        configurable: true,
        get: function () {
            if (this && this.constructor && this.constructor.toString) {
                var arr = this.constructor.toString().match(
                    /function\s*(\w+)/);

                if (arr && arr.length == 2) {
                    return arr[1];
                }
            }

            return undefined;
        },
    });

    /// <summary>
    /// The constructed object (must be after all methods but before the _init definition and call).
    /// </summary>
    var result = {
        // A Test Method to see if we can find the Logger.
        // 
        publicMethod: function (msg) {
            // Log to the first registered Logger.
            // 
            //var logger = assetManager.findAssetByClass("Logger");

            //if (logger && logger.log) {
            //    logger.log(logger.id + " - " + msg);
            //}

            // Log to all registered Loggers.
            // 
            var loggers = assetManager.findAssetsByClass("Logger");

            if (loggers.length > 0) {
                for (i = 0; i < loggers.length; i++) {
                    var l = loggers[i];
                    l.log(l.id + " - " + msg);
                }
            }
        }
    }

    /// <summary>
    /// Readonly Class Property, returns the class.
    /// </summary>
    ///
    /// <param name="result">  The result. </param>
    /// <param name=""class""> The "class". </param>
    Object.defineProperty(result, "class", {
        writable: false,
        enumerable: true,
        configurable: true,
        value: this.class,
    });

    /// <summary>
    /// Write-Once Id Property, returns unique id returned by AssetManager.
    /// 
    /// By the test inside the setter the id property can only be set once (by the AssetManager).
    /// </summary>
    ///
    /// <param name="result"> The result. </param>
    /// <param name=""id"">   The "id". </param>
    Object.defineProperty(result, "id", {
        enumerable: true,
        configurable: true,
        get: function () {
            return _sId;
        },
        set: function (aId) {
            if (_sId.length == 0) {
                _sId = aId;
            }
        },
    });

    /// <summary>
    /// Init Method, Registers Asset.
    /// </summary>
    ///
    /// <param name="claz"> The class name of this class. </param>
    ///
    /// <returns>
    /// The unique identifier generated by the asset manager during registration.
    /// </returns>
    _init = function (claz) {
        // This call registers the instance and sets it's id.
        // 
        return assetManager.registerAssetInstance(result, claz);
    }

    _init(result.class);

    // Subscribe to the example1 event.
    // 
    var testSubscription = pubsubz.subscribe('EventSystem.Init', function (topics, data) {
        console.log("[" + result.id + "]" + "." + topics + ": " + data);
    });

    // Test code to see if id and class can be still changed (should not happen).
    // 
    //result.id = "XYYZ";
    //result.class = "test";

    //cc.log("Class: " + result.class);
    //cc.log("Id: " + result.id);

    return result;
};